/**
 * Expanded Product Catalog - 32 products across all categories
 * Includes: Skin Care, Hair Care, Makeup, Body Care, Fragrance, Tools
 * Features: Variants, Skin Types, Concerns, Reviews, Ingredients
 */

import type { Product, Review } from "./types";

// Reviews generator
const generateReviews = (productId: string, count: number, avgRating: number): Review[] => {
  const templates = [
    { title: "Absolutely love this!", comment: "This product has completely transformed my skin. I've been using it for 3 weeks and the results are incredible." },
    { title: "Holy grail product", comment: "I've tried so many products but this one actually works. The texture is luxurious and absorbs quickly." },
    { title: "Worth every penny", comment: "Yes, it's pricey, but you only need a small amount so it lasts. Quality is exceptional." },
    { title: "Great for sensitive skin", comment: "I have very sensitive skin and this doesn't irritate it at all. Finally found something that works!" },
    { title: "Visible results in 2 weeks", comment: "Started seeing improvements within 2 weeks. Friends have commented on how radiant my skin looks." },
  ];
  const firstNames = ["Sarah", "Emma", "Lisa", "Jennifer", "Maria", "Amanda", "Rachel", "Michelle"];
  
  return Array.from({ length: Math.min(count, 20) }, (_, i) => {
    const t = templates[i % templates.length];
    const rating = Math.max(1, Math.min(5, Math.round(avgRating + (Math.random() - 0.5) * 2)));
    return {
      id: `rev_${productId}_${i}`,
      productId,
      userId: `user_${i}`,
      userName: `${firstNames[i % firstNames.length]} M.`,
      rating,
      title: t.title,
      comment: t.comment,
      helpful: Math.floor(Math.random() * 50) + 1,
      verified: Math.random() > 0.2,
      createdAt: new Date(Date.now() - Math.random() * 90 * 24 * 60 * 60 * 1000).toISOString(),
    };
  });
};

export const MOCK_PRODUCTS: Product[] = [
  // SKIN CARE - 8 products
  {
    id: "p_1",
    name: "Luminous Rose Serum",
    slug: "luminous-rose-serum",
    category: "Skin Care",
    subcategory: "Serums",
    price: 120.0,
    originalPrice: 150.0,
    rating: 4.9,
    reviewCount: 342,
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
    badge: "Sale",
    inStock: true,
    stockCount: 24,
    shortDescription: "Intensely hydrating serum for radiant, glowing skin",
    description: "An intensely hydrating serum powered by rose extract and hyaluronic acid. This lightweight formula penetrates deeply to restore radiance, smooth fine lines, and leave your skin glowing with vitality.",
    ingredients: ["Rosa Damascena (Rose) Extract", "Hyaluronic Acid", "Vitamin C (Ascorbic Acid)", "Niacinamide", "Jojoba Seed Oil", "Squalane", "Glycerin"],
    allergens: ["Rose Extract"],
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_1_30", size: "Travel Size", volume: "30ml", price: 65.0, stockCount: 50, inStock: true, isDefault: false },
      { id: "v_1_50", size: "Regular", volume: "50ml", price: 120.0, originalPrice: 150.0, stockCount: 24, inStock: true, isDefault: true },
      { id: "v_1_100", size: "Value Size", volume: "100ml", price: 210.0, stockCount: 15, inStock: true, isDefault: false },
    ],
    skinTypes: ["Dry", "Combination", "Sensitive", "Normal"],
    concerns: ["Dryness", "Dullness", "Fine Lines", "Hydration"],
    benefits: ["Deeply Hydrates", "Brightens Skin", "Reduces Fine Lines", "Enhances Radiance"],
    howToUse: "Apply 3-4 drops to clean, damp skin morning and evening. Gently press into face and neck. Follow with moisturizer.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "France",
  },
  {
    id: "p_2",
    name: "Velvet Night Cream",
    slug: "velvet-night-cream",
    category: "Skin Care",
    subcategory: "Moisturizers",
    price: 95.0,
    rating: 4.7,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1599305090598-fe179d501227?q=80&w=1000&auto=format&fit=crop",
    isNew: true,
    inStock: true,
    stockCount: 18,
    shortDescription: "Luxurious overnight treatment with retinol",
    description: "A sumptuous overnight treatment that works while you sleep. Enriched with retinol and peptides, it deeply nourishes, firms, and rejuvenates for a visibly smoother, more youthful complexion by morning.",
    ingredients: ["Retinol (Vitamin A)", "Shea Butter", "Ceramide Complex", "Peptide Blend", "Vitamin E", "Aloe Vera Extract", "Sweet Almond Oil"],
    allergens: ["Sweet Almond Oil"],
    images: [
      "https://images.unsplash.com/photo-1599305090598-fe179d501227?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1570194065650-d99fb4a38691?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_2_30", size: "Travel Size", volume: "30ml", price: 48.0, stockCount: 35, inStock: true, isDefault: false },
      { id: "v_2_50", size: "Regular", volume: "50ml", price: 95.0, stockCount: 18, inStock: true, isDefault: true },
    ],
    skinTypes: ["Dry", "Combination", "Normal"],
    concerns: ["Anti-Aging", "Fine Lines", "Firmness", "Uneven Texture"],
    benefits: ["Firms Skin", "Reduces Wrinkles", "Deeply Nourishes", "Repairs Overnight"],
    howToUse: "Apply to cleansed face and neck as the final step in your evening routine. Start with 2-3 times per week to build tolerance.",
    crueltyFree: true,
    vegan: false,
    expiryMonths: 18,
    countryOfOrigin: "Switzerland",
  },
  {
    id: "p_3",
    name: "Golden Glow Face Oil",
    slug: "golden-glow-face-oil",
    category: "Skin Care",
    subcategory: "Face Oils",
    price: 135.0,
    rating: 4.9,
    reviewCount: 276,
    image: "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1000&auto=format&fit=crop",
    isNew: true,
    inStock: true,
    stockCount: 8,
    shortDescription: "24K gold infused oil for instant radiance",
    description: "A luxurious, lightweight face oil that delivers an instant golden glow. Formulated with 24K gold flakes, rosehip oil, and vitamin C to brighten, plump, and deeply nourish your skin.",
    ingredients: ["24K Gold Flakes", "Rosehip Seed Oil", "Vitamin C", "Squalane", "Marula Oil", "Sea Buckthorn Extract", "Tocopherol"],
    images: [
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_3_15", size: "Mini", volume: "15ml", price: 65.0, stockCount: 20, inStock: true, isDefault: false },
      { id: "v_3_30", size: "Regular", volume: "30ml", price: 135.0, stockCount: 8, inStock: true, isDefault: true },
    ],
    skinTypes: ["Dry", "Combination", "Normal", "All Skin Types"],
    concerns: ["Dullness", "Dryness", "Brightening"],
    benefits: ["Instant Glow", "Deeply Nourishes", "Brightens", "Anti-Aging"],
    howToUse: "Warm 2-3 drops between palms and press onto face. Use alone or mix with moisturizer. Can be used morning or evening.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "Italy",
  },
  {
    id: "p_4",
    name: "Hydra-Bloom Moisturizer",
    slug: "hydra-bloom-moisturizer",
    category: "Skin Care",
    subcategory: "Moisturizers",
    price: 88.0,
    originalPrice: 110.0,
    rating: 4.7,
    reviewCount: 198,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1000&auto=format&fit=crop",
    badge: "Sale",
    inStock: true,
    stockCount: 22,
    shortDescription: "72-hour hydration with triple-weight hyaluronic acid",
    description: "A cloud-light yet deeply nourishing moisturizer with triple-weight hyaluronic acid. Locks in 72-hour hydration while protecting against environmental stressors for eternally dewy skin.",
    ingredients: ["Triple-Weight Hyaluronic Acid", "Niacinamide", "Centella Asiatica", "Ceramide III", "Glycerin", "Allantoin", "Panthenol"],
    images: [
      "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1570194065650-d99fb4a38691?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1599305090598-fe179d501227?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_4_50", size: "Regular", volume: "50ml", price: 88.0, originalPrice: 110.0, stockCount: 22, inStock: true, isDefault: true },
      { id: "v_4_100", size: "Family Size", volume: "100ml", price: 155.0, stockCount: 12, inStock: true, isDefault: false },
    ],
    skinTypes: ["Oily", "Combination", "Sensitive", "Normal", "All Skin Types"],
    concerns: ["Dryness", "Hydration", "Oiliness", "Sensitivity"],
    benefits: ["72-Hour Hydration", "Oil-Free", "Soothes", "Strengthens Barrier"],
    howToUse: "Apply to clean face and neck morning and evening. Perfect under makeup as a primer.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "South Korea",
  },
  {
    id: "p_5",
    name: "Petal Soft Cleanser",
    slug: "petal-soft-cleanser",
    category: "Skin Care",
    subcategory: "Cleansers",
    price: 52.0,
    rating: 4.8,
    reviewCount: 445,
    image: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=1000&auto=format&fit=crop",
    badge: "Bestseller",
    inStock: true,
    stockCount: 45,
    shortDescription: "Gentle pH-balanced gel cleanser with rose water",
    description: "A gentle, pH-balanced gel cleanser that removes impurities without stripping. Rose water and aloe vera soothe while micro-foam texture leaves your skin petal-soft and refreshed.",
    ingredients: ["Rose Water", "Aloe Vera Gel", "Glycerin", "Green Tea Extract", "Chamomile Extract", "Allantoin", "Salicylic Acid (0.5%)"],
    images: [
      "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1611930022073-b7a4ba5fcccd?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_5_150", size: "Regular", volume: "150ml", price: 52.0, stockCount: 45, inStock: true, isDefault: true },
      { id: "v_5_250", size: "Jumbo", volume: "250ml", price: 78.0, stockCount: 20, inStock: true, isDefault: false },
    ],
    skinTypes: ["Oily", "Combination", "Sensitive", "Normal", "All Skin Types"],
    concerns: ["Acne", "Oiliness", "Sensitivity", "Pores"],
    benefits: ["Gentle Cleanse", "Balances pH", "Soothes", "Unclogs Pores"],
    howToUse: "Massage onto damp skin in circular motions. Rinse thoroughly. Use morning and evening.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 36,
    countryOfOrigin: "France",
  },
  {
    id: "p_6",
    name: "Vitamin C Brightening Essence",
    slug: "vitamin-c-brightening-essence",
    category: "Skin Care",
    subcategory: "Essences",
    price: 75.0,
    rating: 4.6,
    reviewCount: 156,
    image: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 30,
    shortDescription: "15% Vitamin C for bright, even-toned skin",
    description: "A lightweight essence with 15% pure Vitamin C to fade dark spots, even skin tone, and boost radiance. Ferulic acid and Vitamin E enhance stability and efficacy.",
    ingredients: ["L-Ascorbic Acid (15%)", "Ferulic Acid", "Vitamin E", "Hyaluronic Acid", "Niacinamide", "Centella Asiatica"],
    variants: [
      { id: "v_6_30", size: "Regular", volume: "30ml", price: 75.0, stockCount: 30, inStock: true, isDefault: true },
    ],
    skinTypes: ["Normal", "Combination", "Oily"],
    concerns: ["Dark Spots", "Dullness", "Uneven Texture", "Brightening"],
    benefits: ["Fades Dark Spots", "Brightens", "Antioxidant Protection", "Evens Tone"],
    howToUse: "Apply to clean, dry skin before other serums. Start with every other day. Always use SPF during the day.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 12,
    countryOfOrigin: "USA",
  },
  {
    id: "p_7",
    name: "Soothing Cica Cream",
    slug: "soothing-cica-cream",
    category: "Skin Care",
    subcategory: "Moisturizers",
    price: 68.0,
    rating: 4.8,
    reviewCount: 289,
    image: "https://images.unsplash.com/photo-1617897903246-719242758049?q=80&w=1000&auto=format&fit=crop",
    badge: "Sensitive Skin Favorite",
    inStock: true,
    stockCount: 38,
    shortDescription: "Centella Asiatica cream for sensitive, irritated skin",
    description: "A calming cream powered by Centella Asiatica (Cica) to soothe redness, strengthen the skin barrier, and provide gentle hydration for even the most sensitive skin.",
    ingredients: ["Centella Asiatica Extract", "Madecassoside", "Panthenol", "Allantoin", "Ceramide NP", "Beta-Glucan"],
    variants: [
      { id: "v_7_50", size: "Regular", volume: "50ml", price: 68.0, stockCount: 38, inStock: true, isDefault: true },
    ],
    skinTypes: ["Sensitive", "Dry", "Combination"],
    concerns: ["Redness", "Sensitivity", "Dryness", "Hydration"],
    benefits: ["Soothes Redness", "Strengthens Barrier", "Calms Irritation", "Hydrates"],
    howToUse: "Apply to clean skin morning and evening. Can be used as a daily moisturizer or spot treatment for irritated areas.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "South Korea",
  },
  {
    id: "p_8",
    name: "Pore-Refining Clay Mask",
    slug: "pore-refining-clay-mask",
    category: "Skin Care",
    subcategory: "Masks",
    price: 58.0,
    rating: 4.5,
    reviewCount: 134,
    image: "https://images.unsplash.com/photo-1596755389378-c31d21fd1273?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 25,
    shortDescription: "Kaolin clay mask for deep pore cleansing",
    description: "A purifying clay mask that draws out impurities, absorbs excess oil, and minimizes the appearance of pores. Leaves skin clear, smooth, and refined.",
    ingredients: ["Kaolin Clay", "Bentonite Clay", "Salicylic Acid (2%)", "Tea Tree Oil", "Niacinamide", "Zinc PCA"],
    variants: [
      { id: "v_8_75", size: "Regular", volume: "75ml", price: 58.0, stockCount: 25, inStock: true, isDefault: true },
    ],
    skinTypes: ["Oily", "Combination"],
    concerns: ["Pores", "Acne", "Oiliness"],
    benefits: ["Deep Cleanses", "Minimizes Pores", "Absorbs Oil", "Prevents Breakouts"],
    howToUse: "Apply to clean, dry skin avoiding eye area. Leave for 10-15 minutes. Rinse with warm water. Use 1-2 times per week.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "UK",
  },

  // HAIR CARE - 4 products
  {
    id: "p_9",
    name: "Silk Botanical Shampoo",
    slug: "silk-botanical-shampoo",
    category: "Hair Care",
    subcategory: "Shampoo",
    price: 65.0,
    rating: 4.8,
    reviewCount: 420,
    image: "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 32,
    shortDescription: "Sulfate-free shampoo with argan oil",
    description: "A silky, sulfate-free shampoo infused with argan oil and botanical keratin. Gently cleanses while repairing damaged strands, leaving hair impossibly soft, shiny, and full of life.",
    ingredients: ["Argan Oil", "Botanical Keratin", "Coconut Oil", "Biotin", "Green Tea Extract", "Chamomile Extract", "Provitamin B5"],
    images: [
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1522338242992-e1a54571d50e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_9_250", size: "Travel", volume: "250ml", price: 38.0, stockCount: 40, inStock: true, isDefault: false },
      { id: "v_9_500", size: "Regular", volume: "500ml", price: 65.0, stockCount: 32, inStock: true, isDefault: true },
      { id: "v_9_1000", size: "Family", volume: "1000ml", price: 110.0, stockCount: 18, inStock: true, isDefault: false },
    ],
    concerns: ["Hydration", "Dryness"],
    benefits: ["Sulfate-Free", "Repairs Damage", "Adds Shine", "Gentle Cleanse"],
    howToUse: "Massage into wet hair, lather, and rinse thoroughly. Follow with conditioner for best results.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 36,
    countryOfOrigin: "Morocco",
  },
  {
    id: "p_10",
    name: "Restorative Hair Mask",
    slug: "restorative-hair-mask",
    category: "Hair Care",
    subcategory: "Treatments",
    price: 85.0,
    originalPrice: 100.0,
    rating: 4.6,
    reviewCount: 112,
    image: "https://images.unsplash.com/photo-1608248593842-8d76b1f28b7e?q=80&w=1000&auto=format&fit=crop",
    badge: "Bestseller",
    inStock: true,
    stockCount: 15,
    shortDescription: "Intensive weekly treatment for damaged hair",
    description: "An intensive weekly treatment that transforms damaged, dry hair into silky, lustrous strands. Rich botanical butters and oils deeply condition, repair split ends, and lock in moisture.",
    ingredients: ["Shea Butter", "Avocado Oil", "Hydrolyzed Silk Protein", "Rosemary Extract", "Macadamia Seed Oil", "Honey Extract", "Vitamin E"],
    allergens: ["Honey Extract"],
    images: [
      "https://images.unsplash.com/photo-1608248593842-8d76b1f28b7e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1631730359585-38a4e3a5f2e4?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1597354984706-e1a54571d50e?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_10_200", size: "Regular", volume: "200ml", price: 85.0, originalPrice: 100.0, stockCount: 15, inStock: true, isDefault: true },
      { id: "v_10_500", size: "Pro Size", volume: "500ml", price: 165.0, stockCount: 8, inStock: true, isDefault: false },
    ],
    concerns: ["Dryness", "Hydration"],
    benefits: ["Repairs Damage", "Deep Conditions", "Seals Split Ends", "Adds Softness"],
    howToUse: "Apply to damp hair after shampooing. Leave for 5-10 minutes. Rinse thoroughly. Use weekly or as needed.",
    crueltyFree: true,
    vegan: false,
    expiryMonths: 24,
    countryOfOrigin: "Australia",
  },
  {
    id: "p_11",
    name: "Cashmere Conditioner",
    slug: "cashmere-conditioner",
    category: "Hair Care",
    subcategory: "Conditioner",
    price: 58.0,
    rating: 4.5,
    reviewCount: 312,
    image: "https://images.unsplash.com/photo-1522338242992-e1a54571d50e?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 28,
    shortDescription: "Ultra-rich conditioner for cashmere-soft hair",
    description: "An ultra-rich conditioner that envelops every strand in cashmere-soft luxury. Deep-conditioning botanical oils and silk proteins detangle, smooth, and add brilliant shine.",
    ingredients: ["Silk Amino Acids", "Argan Oil", "Coconut Milk", "Shea Butter", "Wheat Protein", "Jojoba Oil", "Vitamin B5"],
    images: [
      "https://images.unsplash.com/photo-1522338242992-e1a54571d50e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1535585209827-a15fcdbc4c2d?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_11_250", size: "Travel", volume: "250ml", price: 35.0, stockCount: 35, inStock: true, isDefault: false },
      { id: "v_11_500", size: "Regular", volume: "500ml", price: 58.0, stockCount: 28, inStock: true, isDefault: true },
    ],
    concerns: ["Dryness", "Hydration"],
    benefits: ["Detangles", "Adds Shine", "Softens", "Smooths"],
    howToUse: "Apply to mid-lengths and ends after shampooing. Leave for 2-3 minutes. Rinse thoroughly.",
    crueltyFree: true,
    vegan: false,
    expiryMonths: 36,
    countryOfOrigin: "Italy",
  },
  {
    id: "p_12",
    name: "Scalp Revival Serum",
    slug: "scalp-revival-serum",
    category: "Hair Care",
    subcategory: "Treatments",
    price: 72.0,
    rating: 4.7,
    reviewCount: 178,
    image: "https://images.unsplash.com/photo-1526947425960-945c6e72858f?q=80&w=1000&auto=format&fit=crop",
    isNew: true,
    inStock: true,
    stockCount: 22,
    shortDescription: "Pre-shampoo scalp treatment for healthy roots",
    description: "A revitalizing pre-shampoo treatment that balances the scalp microbiome, removes buildup, and promotes healthy hair growth. Tea tree and peppermint invigorate while salicylic acid gently exfoliates.",
    ingredients: ["Salicylic Acid (2%)", "Tea Tree Oil", "Peppermint Oil", "Niacinamide", "Biotin", "Zinc PCA", "Hyaluronic Acid"],
    variants: [
      { id: "v_12_60", size: "Regular", volume: "60ml", price: 72.0, stockCount: 22, inStock: true, isDefault: true },
    ],
    concerns: ["Oiliness", "Sensitivity"],
    benefits: ["Exfoliates Scalp", "Balances Oil", "Promotes Growth", "Removes Buildup"],
    howToUse: "Apply to dry scalp before shampooing. Massage gently. Leave for 10-15 minutes. Shampoo as normal. Use 1-2 times per week.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "USA",
  },

  // MAKEUP - 6 products
  {
    id: "p_13",
    name: "Radiant Skin Foundation",
    slug: "radiant-skin-foundation",
    category: "Makeup",
    subcategory: "Face",
    price: 68.0,
    rating: 4.6,
    reviewCount: 523,
    image: "https://images.unsplash.com/photo-1631730486784-5e4b8c0c6c1e?q=80&w=1000&auto=format&fit=crop",
    badge: "Bestseller",
    inStock: true,
    stockCount: 35,
    shortDescription: "Lightweight foundation with skincare benefits",
    description: "A medium-coverage foundation that looks like skin and feels like skincare. Infused with hyaluronic acid and peptides for a radiant, healthy glow that lasts all day.",
    ingredients: ["Hyaluronic Acid", "Peptide Complex", "Niacinamide", "Vitamin E", "Squalane", "Titanium Dioxide"],
    images: [
      "https://images.unsplash.com/photo-1631730486784-5e4b8c0c6c1e?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1596462502278-27bfdc408d51?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_13_fair", size: "Fair", volume: "30ml", price: 68.0, stockCount: 12, inStock: true, isDefault: false },
      { id: "v_13_light", size: "Light", volume: "30ml", price: 68.0, stockCount: 15, inStock: true, isDefault: false },
      { id: "v_13_medium", size: "Medium", volume: "30ml", price: 68.0, stockCount: 18, inStock: true, isDefault: true },
      { id: "v_13_tan", size: "Tan", volume: "30ml", price: 68.0, stockCount: 10, inStock: true, isDefault: false },
      { id: "v_13_deep", size: "Deep", volume: "30ml", price: 68.0, stockCount: 8, inStock: true, isDefault: false },
    ],
    skinTypes: ["Dry", "Combination", "Normal", "All Skin Types"],
    concerns: ["Dullness", "Hydration"],
    benefits: ["Medium Coverage", "Hydrating", "Long-Wearing", "Skincare Benefits"],
    howToUse: "Apply with brush, sponge, or fingertips. Start at center of face and blend outward. Build coverage as desired.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "France",
  },
  {
    id: "p_14",
    name: "Velvet Matte Lipstick",
    slug: "velvet-matte-lipstick",
    category: "Makeup",
    subcategory: "Lips",
    price: 42.0,
    rating: 4.8,
    reviewCount: 687,
    image: "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 55,
    shortDescription: "Long-wearing matte lipstick in 12 shades",
    description: "A luxurious matte lipstick that delivers intense color payoff in one swipe. Infused with shea butter for comfortable, all-day wear without drying.",
    ingredients: ["Shea Butter", "Jojoba Oil", "Vitamin E", "Candelilla Wax", "Iron Oxides", "Titanium Dioxide"],
    images: [
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1625093742435-6fa192b6fb10?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_14_rouge", size: "Classic Rouge", volume: "3.5g", price: 42.0, stockCount: 20, inStock: true, isDefault: true },
      { id: "v_14_nude", size: "Nude Beige", volume: "3.5g", price: 42.0, stockCount: 18, inStock: true, isDefault: false },
      { id: "v_14_berry", size: "Berry Crush", volume: "3.5g", price: 42.0, stockCount: 17, inStock: true, isDefault: false },
    ],
    benefits: ["Long-Wearing", "Non-Drying", "Intense Color", "Comfortable Matte"],
    howToUse: "Apply directly to lips. For precise application, use a lip liner first. Blot and reapply for extra longevity.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 36,
    countryOfOrigin: "Italy",
  },
  {
    id: "p_15",
    name: "Luminous Setting Powder",
    slug: "luminous-setting-powder",
    category: "Makeup",
    subcategory: "Face",
    price: 52.0,
    rating: 4.5,
    reviewCount: 298,
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=1000&auto=format&fit=crop",
    isNew: true,
    inStock: true,
    stockCount: 28,
    shortDescription: "Translucent powder with subtle glow",
    description: "A finely-milled setting powder that locks makeup in place while adding a soft, luminous finish. Never cakey, never flat.",
    ingredients: ["Silica", "Mica", "Niacinamide", "Squalane", "Titanium Dioxide"],
    variants: [
      { id: "v_15_8", size: "Regular", volume: "8g", price: 52.0, stockCount: 28, inStock: true, isDefault: true },
    ],
    skinTypes: ["All Skin Types"],
    benefits: ["Sets Makeup", "Blurs Pores", "Adds Luminosity", "Long-Lasting"],
    howToUse: "Apply with large fluffy brush to set makeup. Focus on T-zone and areas prone to shine. Reapply as needed throughout the day.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 36,
    countryOfOrigin: "Japan",
  },
  {
    id: "p_16",
    name: "Volumizing Mascara",
    slug: "volumizing-mascara",
    category: "Makeup",
    subcategory: "Eyes",
    price: 38.0,
    rating: 4.7,
    reviewCount: 445,
    image: "https://images.unsplash.com/photo-1631214524020-7e18db9a8f92?q=80&w=1000&auto=format&fit=crop",
    badge: "Ophthalmologist Tested",
    inStock: true,
    stockCount: 42,
    shortDescription: "Dramatic volume with conditioning formula",
    description: "A volumizing mascara that delivers dramatic, clump-free lashes. The conditioning formula with panthenol and vitamin E strengthens lashes while you wear it.",
    ingredients: ["Panthenol", "Vitamin E", "Beeswax", "Carnauba Wax", "Iron Oxides"],
    variants: [
      { id: "v_16_black", size: "Jet Black", volume: "10ml", price: 38.0, stockCount: 25, inStock: true, isDefault: true },
      { id: "v_16_brown", size: "Deep Brown", volume: "10ml", price: 38.0, stockCount: 17, inStock: true, isDefault: false },
    ],
    benefits: ["Volumizes", "Lengthens", "Conditions", "Clump-Free"],
    howToUse: "Wiggle brush at base of lashes and sweep upward. Apply 2-3 coats for maximum volume. Remove with eye makeup remover.",
    crueltyFree: true,
    vegan: false,
    expiryMonths: 6,
    countryOfOrigin: "France",
  },
  {
    id: "p_17",
    name: "Silk Eyeshadow Palette",
    slug: "silk-eyeshadow-palette",
    category: "Makeup",
    subcategory: "Eyes",
    price: 78.0,
    rating: 4.9,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 15,
    shortDescription: "12 silk-infused shades for every occasion",
    description: "A curated palette of 12 silk-infused eyeshadows in matte, shimmer, and metallic finishes. Ultra-blendable, long-wearing, and effortlessly chic.",
    ingredients: ["Mica", "Silk Powder", "Squalane", "Vitamin E", "Jojoba Oil"],
    variants: [
      { id: "v_17_neutrals", size: "Nude Neutrals", volume: "12 x 1.5g", price: 78.0, stockCount: 15, inStock: true, isDefault: true },
    ],
    benefits: ["Highly Pigmented", "Blendable", "Long-Wearing", "Silk-Infused"],
    howToUse: "Use lighter shades as base and brow highlight. Apply medium shades to crease. Use darker shades for definition. Wet brush for intense foil effect.",
    crueltyFree: true,
    vegan: false,
    expiryMonths: 36,
    countryOfOrigin: "Italy",
  },
  {
    id: "p_18",
    name: "Cream Blush Stick",
    slug: "cream-blush-stick",
    category: "Makeup",
    subcategory: "Cheeks",
    price: 36.0,
    rating: 4.6,
    reviewCount: 312,
    image: "https://images.unsplash.com/photo-1591360236480-94956d536b34?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 38,
    shortDescription: "Cream-to-powder blush for a natural flush",
    description: "A creamy blush stick that melts into skin for a natural, dewy flush. The lightweight formula blends seamlessly and lasts all day.",
    ingredients: ["Squalane", "Jojoba Esters", "Vitamin E", "Mica", "Iron Oxides"],
    variants: [
      { id: "v_18_peach", size: "Peach Glow", volume: "6g", price: 36.0, stockCount: 15, inStock: true, isDefault: true },
      { id: "v_18_pink", size: "Rosy Pink", volume: "6g", price: 36.0, stockCount: 12, inStock: true, isDefault: false },
      { id: "v_18_berry", size: "Berry Pop", volume: "6g", price: 36.0, stockCount: 11, inStock: true, isDefault: false },
    ],
    skinTypes: ["All Skin Types"],
    benefits: ["Buildable", "Natural Finish", "Long-Wearing", "Easy Application"],
    howToUse: "Apply directly to cheeks and blend with fingertips or brush. Build up intensity as desired. Can also be used on lips.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "Canada",
  },

  // BODY CARE - 5 products
  {
    id: "p_19",
    name: "Silk Body Lotion",
    slug: "silk-body-lotion",
    category: "Body Care",
    subcategory: "Body Lotion",
    price: 48.0,
    rating: 4.7,
    reviewCount: 356,
    image: "https://images.unsplash.com/photo-1608248543803-ba4f7c23b203?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 40,
    shortDescription: "Luxurious silk-infused body moisturizer",
    description: "A lightweight yet deeply nourishing body lotion infused with silk proteins and shea butter. Absorbs quickly, leaving skin silky smooth with a subtle, elegant scent.",
    ingredients: ["Hydrolyzed Silk Protein", "Shea Butter", "Sweet Almond Oil", "Hyaluronic Acid", "Vitamin E", "Glycerin"],
    allergens: ["Sweet Almond Oil"],
    images: [
      "https://images.unsplash.com/photo-1608248543803-ba4f7c23b203?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_19_250", size: "Regular", volume: "250ml", price: 48.0, stockCount: 40, inStock: true, isDefault: true },
      { id: "v_19_500", size: "Family", volume: "500ml", price: 82.0, stockCount: 22, inStock: true, isDefault: false },
    ],
    concerns: ["Dryness", "Hydration"],
    benefits: ["Deeply Moisturizes", "Silky Texture", "Fast-Absorbing", "Long-Lasting"],
    howToUse: "Apply to damp skin after showering. Massage in circular motions until absorbed. Focus on dry areas like elbows, knees, and heels.",
    crueltyFree: true,
    vegan: false,
    expiryMonths: 24,
    countryOfOrigin: "France",
  },
  {
    id: "p_20",
    name: "Exfoliating Body Scrub",
    slug: "exfoliating-body-scrub",
    category: "Body Care",
    subcategory: "Body Scrub",
    price: 56.0,
    rating: 4.8,
    reviewCount: 278,
    image: "https://images.unsplash.com/photo-1607006344380-b6775a0824a7?q=80&w=1000&auto=format&fit=crop",
    badge: "Spa Favorite",
    inStock: true,
    stockCount: 25,
    shortDescription: "Sugar scrub with coconut oil for glowing skin",
    description: "A luxurious sugar body scrub that gently exfoliates while coconut oil and shea butter deeply nourish. Reveals smooth, radiant skin with a tropical scent.",
    ingredients: ["Cane Sugar", "Coconut Oil", "Shea Butter", "Jojoba Oil", "Vitamin E", "Pineapple Extract"],
    variants: [
      { id: "v_20_200", size: "Regular", volume: "200ml", price: 56.0, stockCount: 25, inStock: true, isDefault: true },
      { id: "v_20_400", size: "Spa Size", volume: "400ml", price: 95.0, stockCount: 12, inStock: true, isDefault: false },
    ],
    concerns: ["Dryness", "Uneven Texture"],
    benefits: ["Gently Exfoliates", "Deeply Nourishes", "Smoothes Skin", "Radiance Boost"],
    howToUse: "Massage onto damp skin in circular motions, focusing on rough areas. Rinse thoroughly. Use 2-3 times per week. Not for face.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 18,
    countryOfOrigin: "Thailand",
  },
  {
    id: "p_21",
    name: "Hydrating Hand Cream",
    slug: "hydrating-hand-cream",
    category: "Body Care",
    subcategory: "Hand Care",
    price: 28.0,
    rating: 4.6,
    reviewCount: 412,
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc408d51?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 60,
    shortDescription: "Rich hand cream for soft, nourished hands",
    description: "A rich, non-greasy hand cream that repairs dry, chapped hands. Absorbs quickly so you can get back to your day with soft, protected hands.",
    ingredients: ["Shea Butter", "Ceramides", "Niacinamide", "Allantoin", "Vitamin E", "Glycerin"],
    variants: [
      { id: "v_21_50", size: "Travel", volume: "50ml", price: 28.0, stockCount: 60, inStock: true, isDefault: true },
      { id: "v_21_100", size: "Home Size", volume: "100ml", price: 48.0, stockCount: 35, inStock: true, isDefault: false },
    ],
    concerns: ["Dryness", "Hydration"],
    benefits: ["Repairs Dry Skin", "Non-Greasy", "Fast-Absorbing", "Protects"],
    howToUse: "Apply to hands as needed throughout the day, especially after washing. Massage into cuticles for extra nourishment.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "UK",
  },
  {
    id: "p_22",
    name: "Soothing Body Wash",
    slug: "soothing-body-wash",
    category: "Body Care",
    subcategory: "Body Wash",
    price: 42.0,
    rating: 4.7,
    reviewCount: 334,
    image: "https://images.unsplash.com/photo-1556228720-195a9e1f8ad2?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 45,
    shortDescription: "Gentle, pH-balanced body cleanser",
    description: "A gentle, sulfate-free body wash that cleanses without stripping skin's natural moisture. Chamomile and oat soothe while maintaining skin's delicate pH balance.",
    ingredients: ["Oat Extract", "Chamomile Extract", "Aloe Vera", "Glycerin", "Coconut-Derived Surfactants", "Panthenol"],
    variants: [
      { id: "v_22_300", size: "Regular", volume: "300ml", price: 42.0, stockCount: 45, inStock: true, isDefault: true },
      { id: "v_22_500", size: "Family", volume: "500ml", price: 68.0, stockCount: 25, inStock: true, isDefault: false },
    ],
    skinTypes: ["Sensitive", "Dry", "All Skin Types"],
    concerns: ["Sensitivity", "Dryness"],
    benefits: ["Gentle Cleanse", "Sulfate-Free", "Soothes", "Maintains pH"],
    howToUse: "Apply to wet skin or loofah. Lather and rinse thoroughly. For external use only. Follow with body lotion.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 36,
    countryOfOrigin: "Canada",
  },
  {
    id: "p_23",
    name: "Mineral Sunscreen SPF 50",
    slug: "mineral-sunscreen-spf50",
    category: "Body Care",
    subcategory: "Sun Care",
    price: 58.0,
    rating: 4.5,
    reviewCount: 189,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?q=80&w=1000&auto=format&fit=crop",
    badge: "Dermatologist Recommended",
    inStock: true,
    stockCount: 30,
    shortDescription: "100% mineral sunscreen for face and body",
    description: "A lightweight, 100% mineral sunscreen with zinc oxide and titanium dioxide. Protects against UVA/UVB rays without leaving a white cast. Reef-safe and gentle on sensitive skin.",
    ingredients: ["Zinc Oxide (20%)", "Titanium Dioxide (5%)", "Squalane", "Vitamin E", "Green Tea Extract"],
    variants: [
      { id: "v_23_100", size: "Face Size", volume: "100ml", price: 38.0, stockCount: 20, inStock: true, isDefault: false },
      { id: "v_23_150", size: "Body Size", volume: "150ml", price: 58.0, stockCount: 30, inStock: true, isDefault: true },
    ],
    skinTypes: ["Sensitive", "All Skin Types"],
    concerns: ["Sensitivity"],
    benefits: ["SPF 50 Protection", "100% Mineral", "Reef-Safe", "Non-Greasy"],
    howToUse: "Apply liberally 15 minutes before sun exposure. Reapply every 2 hours or after swimming or sweating. Use daily as last step in skincare routine.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 24,
    countryOfOrigin: "Australia",
  },

  // FRAGRANCE - 4 products
  {
    id: "p_24",
    name: "Rose de Luxe Eau de Parfum",
    slug: "rose-de-luxe-edp",
    category: "Fragrance",
    subcategory: "Eau de Parfum",
    price: 195.0,
    rating: 4.9,
    reviewCount: 456,
    image: "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000&auto=format&fit=crop",
    badge: "Signature Scent",
    inStock: true,
    stockCount: 20,
    shortDescription: "Sophisticated rose fragrance with amber notes",
    description: "An exquisite rose fragrance that captures the essence of a blooming garden at dawn. Turkish rose, peony, and soft amber create a timeless, feminine scent that lingers beautifully.",
    ingredients: ["Turkish Rose Absolute", "Peony", "Amber", "Musk", "Bergamot", "Sandalwood"],
    allergens: ["Fragrance (Parfum)"],
    images: [
      "https://images.unsplash.com/photo-1541643600914-78b084683601?q=80&w=1000&auto=format&fit=crop",
      "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop",
    ],
    variants: [
      { id: "v_24_30", size: "Travel", volume: "30ml", price: 95.0, stockCount: 15, inStock: true, isDefault: false },
      { id: "v_24_50", size: "Regular", volume: "50ml", price: 195.0, stockCount: 20, inStock: true, isDefault: true },
      { id: "v_24_100", size: "Luxury", volume: "100ml", price: 285.0, stockCount: 8, inStock: true, isDefault: false },
    ],
    benefits: ["Long-Lasting", "Sophisticated", "Timeless", "Elegant"],
    howToUse: "Spray on pulse points: wrists, neck, and behind ears. Do not rub. Allow to dry naturally. Layer with matching body lotion for extended wear.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 60,
    countryOfOrigin: "France",
  },
  {
    id: "p_25",
    name: "Citrus Bloom Eau de Toilette",
    slug: "citrus-bloom-edt",
    category: "Fragrance",
    subcategory: "Eau de Toilette",
    price: 125.0,
    rating: 4.7,
    reviewCount: 234,
    image: "https://images.unsplash.com/photo-1594035910387-fea47794261f?q=80&w=1000&auto=format&fit=crop",
    isNew: true,
    inStock: true,
    stockCount: 25,
    shortDescription: "Fresh citrus fragrance with white florals",
    description: "A vibrant, uplifting fragrance that opens with sparkling citrus and settles into a heart of white jasmine and neroli. Perfect for everyday elegance.",
    ingredients: ["Italian Bergamot", "Sicilian Lemon", "Jasmine", "Neroli", "White Musk", "Cedarwood"],
    allergens: ["Fragrance (Parfum)", "Linalool", "Limonene"],
    variants: [
      { id: "v_25_50", size: "Regular", volume: "50ml", price: 125.0, stockCount: 25, inStock: true, isDefault: true },
      { id: "v_25_100", size: "Large", volume: "100ml", price: 175.0, stockCount: 12, inStock: true, isDefault: false },
    ],
    benefits: ["Fresh", "Uplifting", "Daytime Perfect", "Elegant"],
    howToUse: "Spritz lightly on pulse points. Perfect for daytime wear. Refresh throughout the day as desired.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 60,
    countryOfOrigin: "Italy",
  },
  {
    id: "p_26",
    name: "Velvet Amber Perfume Oil",
    slug: "velvet-amber-perfume-oil",
    category: "Fragrance",
    subcategory: "Perfume",
    price: 145.0,
    rating: 4.8,
    reviewCount: 178,
    image: "https://images.unsplash.com/photo-1595425970377-c9703cf48b6d?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 15,
    shortDescription: "Concentrated perfume oil with amber and vanilla",
    description: "A luxurious, alcohol-free perfume oil that melts into skin for an intimate, long-lasting scent. Rich amber, vanilla, and musk create a warm, sensual aura.",
    ingredients: ["Amber Resin", "Madagascar Vanilla", "White Musk", "Sandalwood", "Coconut Oil Base"],
    allergens: ["Fragrance (Parfum)"],
    variants: [
      { id: "v_26_10", size: "Rollerball", volume: "10ml", price: 145.0, stockCount: 15, inStock: true, isDefault: true },
    ],
    benefits: ["Alcohol-Free", "Long-Lasting", "Intimate Scent", "Travel-Friendly"],
    howToUse: "Roll onto pulse points. The warmth of your skin will release the fragrance throughout the day. Perfect for sensitive skin or scent layering.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 48,
    countryOfOrigin: "Morocco",
  },
  {
    id: "p_27",
    name: "Botanical Body Mist",
    slug: "botanical-body-mist",
    category: "Fragrance",
    subcategory: "Body Mist",
    price: 48.0,
    rating: 4.5,
    reviewCount: 267,
    image: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 35,
    shortDescription: "Light, refreshing body mist with botanical extracts",
    description: "A refreshing body mist infused with botanical extracts that hydrates skin while leaving a delicate, natural scent. Perfect for a quick refresh throughout the day.",
    ingredients: ["Rose Water", "Aloe Vera", "Glycerin", "Green Tea Extract", "Chamomile Extract", "Natural Fragrance"],
    variants: [
      { id: "v_27_100", size: "Regular", volume: "100ml", price: 48.0, stockCount: 35, inStock: true, isDefault: true },
    ],
    benefits: ["Hydrating", "Lightweight", "Refreshing", "Natural Scent"],
    howToUse: "Spray onto body and hair from 6 inches away. Reapply throughout the day for a fresh burst of fragrance and hydration.",
    crueltyFree: true,
    vegan: true,
    expiryMonths: 18,
    countryOfOrigin: "France",
  },

  // TOOLS & ACCESSORIES - 5 products
  {
    id: "p_28",
    name: "Rose Quartz Face Roller",
    slug: "rose-quartz-face-roller",
    category: "Tools & Accessories",
    subcategory: "Skincare Tools",
    price: 68.0,
    rating: 4.6,
    reviewCount: 423,
    image: "https://images.unsplash.com/photo-1616394584738-fc6e612e71b9?q=80&w=1000&auto=format&fit=crop",
    badge: "Bestseller",
    inStock: true,
    stockCount: 30,
    shortDescription: "Natural rose quartz for facial massage",
    description: "A genuine rose quartz face roller to de-puff, stimulate circulation, and enhance product absorption. The cooling stone helps relax facial muscles and promote lymphatic drainage.",
    ingredients: [],
    variants: [
      { id: "v_28_single", size: "Single Roller", volume: "1pc", price: 68.0, stockCount: 30, inStock: true, isDefault: true },
      { id: "v_28_set", size: "Roller + Gua Sha Set", volume: "2pc", price: 98.0, stockCount: 20, inStock: true, isDefault: false },
    ],
    benefits: ["De-Puffs", "Boosts Circulation", "Enhances Absorption", "Relaxing"],
    howToUse: "Use after applying serum or oil. Roll upward and outward from center of face. Store in refrigerator for extra cooling effect. Clean after each use.",
    crueltyFree: true,
    vegan: true,
    countryOfOrigin: "China",
  },
  {
    id: "p_29",
    name: "Luxury Makeup Brush Set",
    slug: "luxury-makeup-brush-set",
    category: "Tools & Accessories",
    subcategory: "Brushes",
    price: 185.0,
    rating: 4.9,
    reviewCount: 289,
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 18,
    shortDescription: "10-piece professional brush set",
    description: "A curated collection of 10 professional-quality makeup brushes with synthetic bristles and elegant rose gold handles. Includes face and eye brushes for a complete look.",
    ingredients: [],
    variants: [
      { id: "v_29_set", size: "Complete Set", volume: "10 brushes", price: 185.0, stockCount: 18, inStock: true, isDefault: true },
    ],
    benefits: ["Professional Quality", "Synthetic Bristles", "Complete Set", "Elegant Design"],
    howToUse: "Use each brush for its designated purpose. Clean brushes weekly with gentle soap or brush cleaner. Lay flat to dry to maintain shape.",
    crueltyFree: true,
    vegan: true,
    countryOfOrigin: "Japan",
  },
  {
    id: "p_30",
    name: "Silk Sleep Mask",
    slug: "silk-sleep-mask",
    category: "Tools & Accessories",
    subcategory: "Accessories",
    price: 55.0,
    rating: 4.7,
    reviewCount: 334,
    image: "https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 40,
    shortDescription: "100% mulberry silk sleep mask",
    description: "A luxurious 100% mulberry silk sleep mask that blocks light while protecting delicate eye skin. The silk helps retain moisture and prevent sleep lines.",
    ingredients: [],
    variants: [
      { id: "v_30_blush", size: "Blush Pink", volume: "1pc", price: 55.0, stockCount: 15, inStock: true, isDefault: true },
      { id: "v_30_charcoal", size: "Charcoal", volume: "1pc", price: 55.0, stockCount: 12, inStock: true, isDefault: false },
      { id: "v_30_ivory", size: "Ivory", volume: "1pc", price: 55.0, stockCount: 13, inStock: true, isDefault: false },
    ],
    benefits: ["Blocks Light", "Prevents Wrinkles", "Retains Moisture", "100% Silk"],
    howToUse: "Adjust strap for comfortable fit. Wear during sleep or meditation. Hand wash gently with mild soap. Air dry only.",
    crueltyFree: true,
    vegan: false,
    countryOfOrigin: "China",
  },
  {
    id: "p_31",
    name: "Reusable Cotton Rounds",
    slug: "reusable-cotton-rounds",
    category: "Tools & Accessories",
    subcategory: "Skincare Tools",
    price: 24.0,
    rating: 4.8,
    reviewCount: 567,
    image: "https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=1000&auto=format&fit=crop",
    badge: "Eco Favorite",
    inStock: true,
    stockCount: 85,
    shortDescription: "Set of 8 washable bamboo cotton rounds",
    description: "A sustainable alternative to disposable cotton pads. These soft, washable bamboo rounds are perfect for applying toner, removing makeup, or applying skincare products.",
    ingredients: [],
    variants: [
      { id: "v_31_white", size: "White", volume: "8pc", price: 24.0, stockCount: 45, inStock: true, isDefault: true },
      { id: "v_31_beige", size: "Natural Beige", volume: "8pc", price: 24.0, stockCount: 40, inStock: true, isDefault: false },
    ],
    benefits: ["Eco-Friendly", "Reusable", "Soft", "Durable"],
    howToUse: "Use as you would disposable cotton rounds. Rinse after use and wash with laundry in mesh bag. Air dry or tumble dry low.",
    crueltyFree: true,
    vegan: true,
    countryOfOrigin: "India",
  },
  {
    id: "p_32",
    name: "Makeup Organizer",
    slug: "makeup-organizer",
    category: "Tools & Accessories",
    subcategory: "Storage",
    price: 78.0,
    rating: 4.5,
    reviewCount: 198,
    image: "https://images.unsplash.com/photo-1596462502278-27bfdc408d51?q=80&w=1000&auto=format&fit=crop",
    inStock: true,
    stockCount: 22,
    shortDescription: "Acrylic rotating makeup organizer",
    description: "A stylish, rotating acrylic organizer with multiple compartments for all your beauty essentials. Keeps products visible, accessible, and beautifully displayed.",
    ingredients: [],
    variants: [
      { id: "v_32_standard", size: "Standard", volume: "1pc", price: 78.0, stockCount: 22, inStock: true, isDefault: true },
    ],
    benefits: ["360° Rotation", "Multiple Compartments", "Clear Design", "Sturdy"],
    howToUse: "Assemble according to instructions. Place on vanity or bathroom counter. Rotate to access different sections. Wipe clean with damp cloth.",
    crueltyFree: true,
    vegan: true,
    countryOfOrigin: "Taiwan",
  },
];

// Populate reviews
MOCK_PRODUCTS.forEach((product) => {
  product.reviews = generateReviews(product.id, Math.min(product.reviewCount, 20), product.rating);
});
